language: java

jdk:
- openjdk11

sudo: false
env:
  global:
  #key for github
  #GITHUB_OAUTH_TOKEN
  - secure: "cvMdXjM4RsNKbmAlzEqG8+HKNV6e3S3rqaZ8rq7nuWZJ+YaQvYYTWx7CVR0XBqCg/FUyUtpjLQYc+GN9hXhC68O2MeQ5a50AxvuBmfWddqhwJZiqFzSfsyNELFfL5wllPJPl6+Mkqne9fju4axzi4AKHuvlMUb1EhpxF97iwIVUK6lnrZu7zbtaEeTDuRYuQVhT+a3YSmkMcnP4Z9XqLoY1C5lqKqUBnnfmOrA4kq+MRjGD6by8/L94i9yv15C0zX/7z13ByIuRra1Vw3XPLzr7K+LQIZ4OxydCbeFPOd50lHfBMRFcz9hunMUJje3ueQ9bg4Jrkpx7YNyjOsYbKlWD+DF+elTcOeUgOh7LMyCfqDbyiGa4YzAhgy98Dl2SZLVHgQHXSPRiFzm5ERRf9b8kPM9oWqUDuWunZBAnANxn4DSJ4FSAXIoMg+LcbBwjz0QMAWfvKdL4O4Zcbo3mSVTKTuHcnJKAhRKPXnDd/EPNKp0N5gJ77anR73wjn2mwEHbKSWKoTO9oUjSyeDSH2bTc7XuBTPtbMCgt59g3hTeVehuTdf/5H8i+qMJ8iQkvil/1xVrafV6f9kKJf8rcU/d0qcfgd6VppI4NVqVRyp7AOeSY93gs1dLzgPFnP5bH78/tlpQqLEJp3dvilXEbYGuh6nK93tLFG7MKBXikZY+A="
  - environment=test
  #sonatype credentials
  #OSSRH_JIRA_USERNAME
  - secure: "M9dh3BnLr24AUSllHMOFgMHaMDeeE/7RyvReYIMbikAv2FwVeFfuIzjb8GwC1x8D9oKV21uAAH+yTUcXq3tVCw8ar/HJapJfbBV1ddC2vad+YBKrFi005iEGyKe1ehJa2UXLjL2nJXGd2RDztQ+ngnU+ICXIm5R8dmrYB+P24L5y+MgYjaoq9V2I3rW46beBT4yZra45TUrmQGTywxVfvBAJQnQYKe47hHBIOzkjRpXkeKNryTIRfrXtU4re+h0kjF6z7lLlZb862LWa7gfP7XU8rMaMAlVQBF60wxB6/0GxuS6ghZPE7EltP0sQBSFGbxq+TWimhtEJe7HGLFPbquz66ROipb+yzqWASzgRG2PkFj+i3CIZQJqlqHiHcsfwlWuG/f/+kRUHzcDhzhtPejm3/yeNJ75ckTz4dSuyhuCP/NHRp2e3SQjyKokZnpnTokgA0fW3JI1/+ZMVloyN3n6DfwTluM57DZ1dV5+fvMF7N1C4RPG08LvF3An6QACDhb+FgUgIQ33ikNJCPoavbdK8IEbuHmQwaDhYGIVcFnqNOrwcjPHGkXXMhouPbRYQ2JC9sw5gBxpu97kRIOCiKo5EvfOnWyIPwWU1lI23O/lBCzKYiP6O3GnVLhJ6CK5JseaTGx0xguWnuQLZFNa0yZHRXeTTuzRMZ4ul1SS7JFI="
  #OSSRH_JIRA_PASSWORD
  - secure: "PB8WdHYj9D3hg4qTC4XqaRXyhSciblgOXFVTOm4nSwFRi1bkhJPXV+aHJppsZO3vxvkQfoIZRBznyiHSNOPpYOdAn/2RpA/9XFWBJGyzzbmWPDTeX3H/rNql4agf6tz1qlcYg1uS4/Tj2RswsoVg5utCbg2Sf8kny1yNK/Kdc2V/ns00069MzaWiYhV5LIXWL1QWr3MSaDYGzWyM2QBHlafylN5KBAK65lbGDvy9IOZH3avGL8Lfoup4o4f13QMURtn9zEnYAM3DVuGdxecsqdVyYWtte/YszwKK2jQU1SQt8T9AdLFEf58gsxzqFd/EX/jF4/aXsEPaJ3mlldaiyi15Ef6g8zhebSReinJ7pyxjUnNtm78S97Pa6GuktQfOhMhbKQ5b/juudCWc71ZTjut8bwFcQ3XdjcyuOPHsf3UG9xobIxtV8tI8X9XvPFLCT2fR7Io0llfNFVOno01LaMQ8gLBq19twGXymDpM1dVoce+mR+hhILF/tY7KxqjJRL7IOtSApImKetpVEF4pY/6h8VP7ZJFRadztrWbhx/QBzkUCn3m39wP//MQfkC7e6fOpq3xTifCO1SZPvTTwKYBh2K30yaS3QkvVGmPaAd/OlAb9fPEZgYvFkzTRiu5f/6bCaGqLqGMzoqoqlQGkyKNC848fKm0FeAFmbBzgrs6k="
  #signing key
  #GPG_KEY_NAME
  - secure: "26JOlNEoTnK6GTs/MSCfqZPczi8b7p0Nu96MG5Qb/Bxhvn57lq/Fs4cSKnG/8F/2uFBoUQYDU+t2R/KUWufBCu82de3rzoZZCRVvhJtWDnmxwTYcpE5j6w56wemWWq/jS5Qpsl0ZONsTyniGo9FyG6OQYm9n0523axSZeUcT4Lpv/h+f2Pmr5le6XppzSRBHajGSGxuQQHqEYZ1PbCO6m4iloqVtc0wF35LFMY2S0YKlrE35h5U6j6StAyx3NUF1ZIEXogQ4dqgCmPv9it8hDbBAJbPuOfgEjhddTR2keY9eP7+lxdBwgkJOAZFsBL/NpL1g5LSATx170CuoWmAkPZ0l/6NA515H/Op+dg/c+u0aVkRm2mZLkJz33FwVD67WMwU7ISNzkx2Q8W8j+cCsr+tywDd2r26+zrLhNXboVgwbAZIYJx3ax88wftOzGXlfZ4nVZky87nb1Py/Fp8brbTo+Rci3F9INpZ+22OFJXjXS9a648fJ1gLOg0/Ov5Pco0I4q5mEE2pcMBb/IGn4ufWTJBJGddqW6r+/xBol2cokHF7zNUMOcztIA8sq/vG1LoReJ+zpEuEJoszhXKZiRs60tCbceKbPvRSTC5agX3eTmvOA00TIg+bRhIhso4rzxD+iB9ijq2a93/qj/OcO63IUebqfVfQwaHWTulr4s0GA="
  #GPG_PASSPHRASE
  - secure: "y1Qdse//mi7R29M0TI78DLw4mDUxfVF4vt9v6zT7kmtMLetaPL1sKFelVxsDXNJ7MHP29OXwhL2rqgJofX1g8Z4ViftbSVKlODhy3wMVLSe+xCIrcsa/GABHU+g18oxHl4Jnnp8l3jrTComuSr9bKXdnXpXqMj9nO/jkGmZ2XFMRFoQ4/AOtr5QqGHF5+caeigpFcyZlSrgqa8tUEHk490uiRIAQ0X6dMQmvFmEcB+8//L1iiCYMQ19RKEtAUZOz023aFYAvr9sxjaGUF/aBD7VpzTCyAhxCIuQLYtr+5G2Wr+9p2mqM+rjgq4a2Hq3ftgbjvlsns83/ZYFtW4vWDgj5QKpe7+zfaHOtsi0NoXhEzCh7y1KFqZDolQzLXR/TUrxJteJj7b5zi9f5x3pE/A6RJZVEhzl1TYdrUQLxksril1SkcK6DiYF6WIVPyvvLbSAU1zIslmavqP4bgGIs4vMKGI/dC69dYj+0SNtThFP3wlpak0ONYpXp0JUO7ADQaS6FcKiDKJiybA+z1hxAz4tchpi3RsS0nFeei4Cr1BBv2FBJO92UYc4XqrOvzghFn9oTDVhES7N+Vw/k93Rh/mpSXKjVbzUq3qUBni6iw+fTaB/XxxgTwCf7BXYOgJWkIvLbvNjTBLXDMwzEldq09uWhIFwkdRri7YlldJA8edc="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "cGfl6Gz6s3/QPClfcNg7xqlueOSIMFNGLm/X5xDTARoNIM79JhyPrgJc8zO+vImhkDoYZCYnuHD+LZ7LeN9O3OvcPjAURMiwsJODd4iaMcv8l2gqyo/8055Oz+gbAX+CLAaBDIrKzkBoXLKABzJqaUG81AvWSzKrKFvXgMk9G7ODKXo8+NJcakXs/JIAD9SD2DxWlP4rLAo1n5lh7gZC9jB2uTpymFbLUtig2kK+pl4ON0+J4p5hxT/1fsrD7rUY5zYCqyW6+YO2glyz3kgl7EqczO/gi11dptM9ln/cuErJJQMqLpNlGS9fzMtUrfoWu7fUZgMNTbn1zNdXnc/slwh348e4c82PqDKin3Q0UDUtfAneGDULun8xeTF8vQj+ZHk1EcFLac3G+ApPRHzGUWz5fuTaqBvCntkJaHfGKZPhrL9zg7XZVz3j+si0Inzjppig68Q5878CMAD9tjccpYbWwh/zLeRxX5GgokI30QTaLeJZRFMGJCE0sFyOQ0lI6ESdFNK10uxTxB2XxMaV66HSjZ0Jt/wkW5Cnsb/e16VmEajhdDVIgRV+sOLjYQiydMH8h9QglFihgrNIk7VecNPkRYWqZqXH2q3EcHKZaqz7QIA55f1JCMONtWwcnD/1y02h0aaKaL+0pkZ8I6v8K145l34L3moedJiX2r4jeOo="

branches:
  only:
  - develop
  - master

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
- travis_wait 50 mvn clean jacoco:prepare-agent install jacoco:report -P !build-extras
- mvn site -Djacoco.skip -DskipTests -P !build-extras
- sonar-scanner

cache:
  directories:
  - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
- ./cd/before-deploy.sh
- ./cd/deploy.sh
